2019-03-30 22:27:55,017 ERROR: Exception on /register [POST] [in /home/ahmnouira/Desktop/Ahmed_blog/Flask_Blog-master/venv/lib/python3.5/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/ahmnouira/Desktop/Ahmed_blog/Flask_Blog-master/venv/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ahmnouira/Desktop/Ahmed_blog/Flask_Blog-master/venv/lib/python3.5/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ahmnouira/Desktop/Ahmed_blog/Flask_Blog-master/venv/lib/python3.5/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ahmnouira/Desktop/Ahmed_blog/Flask_Blog-master/venv/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/ahmnouira/Desktop/Ahmed_blog/Flask_Blog-master/venv/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ahmnouira/Desktop/Ahmed_blog/Flask_Blog-master/venv/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ahmnouira/Desktop/Ahmed_blog/Flask_Blog-master/app/routes.py", line 101, in register
    user.set_password(form_reg.password.data)
AttributeError: 'function' object has no attribute 'set_password'
